### ISSUE TITLE
Adding project and repo name to the Slack notifications

### ISSUE THREAD

**Issue by burakkantarci** [runforesight/foresight-issues#11]
Hi all, There is no repo or project name on slack notifications on GitHub action statuses. 

Feedback by Serkan, Cenoa

**Comment by suleymanbarman** [comment]
Added 

- repo
- workflow
- headCommit 

to notification result on Slack message 



<img width="702" alt="image" src="https://user-images.githubusercontent.com/3482186/199025874-b8c2afda-a39d-4379-96e9-5f5db18b4476.png">

Are those parameter enough to understand which workflows has been run?
