### ISSUE TITLE
Showing source branch for PRs

### ISSUE THREAD

**Issue by stianst** [runforesight/foresight-issues#4]
Throughout the UI the source branch is shown for PRs. 

![image](https://user-images.githubusercontent.com/2271511/194554357-966b3317-75de-4fc5-8ac0-bbd13a435e4b.png)

![image](https://user-images.githubusercontent.com/2271511/194554435-0065ece2-213f-442f-be30-abfb43ad962e.png)

![image](https://user-images.githubusercontent.com/2271511/194554565-6cde7b95-e0c1-4b62-abcd-a2fbeadcb69d.png)

What I would like to see is only branches from my repository throughout, and not the "random" branch folks send their PRs from.

**Comment by suleymanbarman** [comment]
@burakkantarci will investigate alternatives to hide fork branches which can be seen optionally.

**Comment by stianst** [comment]
Wonder if anyone will ever care about the "fork/source branch" at all?

**Comment by burakkantarci** [comment]
🚀 Launched: [https://docs.runforesight.com/how-to/hide-forks](https://docs.runforesight.com/how-to/hide-forks)
