### ISSUE TITLE
Make it easier to filter on a single workflow

### ISSUE THREAD

**Issue by stianst** [runforesight/foresight-issues#6]
We have quite a few workflows (and more coming ;)). When I want to view a single workflow it's quite inconvenient to have to deselect all other workflows:

![image](https://user-images.githubusercontent.com/2271511/194555441-27d229ec-55ff-4976-b03f-bd8e805c9454.png)

**Comment by stianst** [comment]
Related to https://github.com/runforesight/foresight-issues/issues/3

**Comment by burakkantarci** [comment]
![workflow-filter-improvement](https://user-images.githubusercontent.com/5147390/195839162-761b38e1-a5da-42b8-8589-a26af71e01d9.png)
